### ISSUE TITLE
EasyFarmingScript

### ISSUE THREAD

**Issue by ste4fan** [TomWright/TribalWarsScripts#1]
I love that script it helps alot but i have a question

Everytime i run sripts it also concludes 1 scout with x amount lc when runing and that is by deafult so i was woundering if you can somehow make it just to calculate how much lc needs to be sent like normal but without any scout in attack?

**Comment by TomWright** [comment]
I assume you are using the easy-farm-report script?
This is the script that you run from the report screen that works out how many LC to send in order to take all of the resources (assuming they are still there).

I have made a change to the script to allow you to disable to scout.

Use the following script and you should get your desired result. I have not tested this as I no longer play TribalWars. Please let me know if there are any issues.

    javascript:$.getScript('https://tw.tomwright.me/get-script/easy_farm.js');window.setupTomWrightTribalWars = function (callback) {callback = callback||function () {};TomWrightTribalWars.EasyFarm.Report.sendScout = false;callback();};void 0;

**Comment by ste4fan** [comment]
Works completely like I wanted only lc :)) Thank you very much good Sir ! Have great day/night

**Comment by ste4fan** [comment]
hey im sorry to anoyy you again but the easy farming script is not working
( maybe is because of some update from tribal wars team but can you please
look it up what is wrong with it )

**Comment by ste4fan** [comment]
hey im sorry to anoyy you again but the easy farming script is not working
( maybe is because of some update from tribal wars team but can you please
look it up what is wrong with it )

**Comment by TomWright** [comment]
I'm afraid it isn't working as it is no longer live. I am in the middle of migrating web hosts and when this is done the script will function again.
I'm hoping to deal with it over the weekend.

**Comment by ste4fan** [comment]
Okay i wll keep this page in my tabs to see when its updated

I hope it will work again when everything is done 

Thank you for quick respond

**Comment by TomWright** [comment]
Hi @ste4fan,

You should be able to use the script as normal now.
If you are still having problems please open a new issu.

Enjoy!
